config/routes.rb
Rails.application.routes.draw do
  resources :waypoints
  resources :vehicles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'show', :to => 'vehicles#index'  
  post 'api/v1/gps', :to => 'waypoints#api_v1_gps'  
  get 'api/v1/gps', :to => 'waypoints#api_v1_gps'  
  root :to => redirect('/show')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
	has_many :waypoints, dependent: :delete_all
	def last_waypoint
		self.waypoints.order(:sent_at).last
	end
end

app/models/waypoint.rb
class Waypoint < ApplicationRecord
  belongs_to :vehicle
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:identifier)
    end
end

app/controllers/waypoints_controller.rb
class WaypointsController < ApplicationController
  before_action :set_waypoint, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => [:api_v1_gps]
  # GET /waypoints
  # GET /waypoints.json
  def index
    @waypoints = Waypoint.all
  end

  # GET /waypoints/1
  # GET /waypoints/1.json
  def show
  end

  # GET /waypoints/new
  def new
    @waypoint = Waypoint.new
  end

  # GET /waypoints/1/edit
  def edit
  end

  # POST /waypoints
  # POST /waypoints.json
  def create
    @waypoint = Waypoint.new(waypoint_params)

    respond_to do |format|
      if @waypoint.save
        format.html { redirect_to @waypoint, notice: 'Waypoint was successfully created.' }
        format.json { render :show, status: :created, location: @waypoint }
      else
        format.html { render :new }
        format.json { render json: @waypoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /api/v1/gps
  # POST /api/v1/gps
  # {
  #   "latitude": 20.23,
  #   "longitude": -0.56,
  #   "sent_at": 2016-06-02 20:45:00",
  #   "vehicle_identifier": "HA-3452"
  # }
  def api_v1_gps
    @waypoint = Waypoint.new(
      {
        latitude: params[:latitude],
        longitude: params[:longitude], 
        sent_at: params[:sent_at], 
        vehicle_id: Vehicle.find_or_create_by({identifier: params[:vehicle_identifier]}).id
      }
    )

    ActionCable.server.broadcast "notifications", {html: "<div>Information updated at #{DateTime.now }</div>"}

    respond_to do |format|
      if @waypoint.save
        format.html { render :show, status: :created, location: @waypoint }
        format.json { render :show, status: :created, location: @waypoint }
      else
        format.html { render json: @waypoint.errors, status: :unprocessable_entity }
        format.json { render json: @waypoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waypoints/1
  # PATCH/PUT /waypoints/1.json
  def update
    respond_to do |format|
      if @waypoint.update(waypoint_params)
        format.html { redirect_to @waypoint, notice: 'Waypoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @waypoint }
      else
        format.html { render :edit }
        format.json { render json: @waypoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waypoints/1
  # DELETE /waypoints/1.json
  def destroy
    @waypoint.destroy
    respond_to do |format|
      format.html { redirect_to waypoints_url, notice: 'Waypoint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waypoint
      @waypoint = Waypoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waypoint_params
      params.require(:waypoint).permit(:latitude, :longitude, :sent_at, :vehicle_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/waypoints_helper.rb
module WaypointsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waypoints</title>
    <%= csrf_meta_tags %>

	<script src="//maps.google.com/maps/api/js?key=AIzaSyA6PA4ZnHlcRlvP-nFsBQW7kbuwBD04gbY"></script>
  	<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>	    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  
	
  <link rel="manifest" href="/manifest.json" />
<meta name="apple-mobile-web-app-capable" content="yes"></head>

  <body>
    <div id="notifications"></div>
    <%= yield %>
  </body>
  
  <%= javascript_include_tag 'application' %>


</html>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :identifier %>
    <%= form.text_field :identifier, id: :vehicle_identifier %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/_show_data.html.erb
<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.identifier %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>
<% #AIzaSyA6PA4ZnHlcRlvP-nFsBQW7kbuwBD04gbY %>



<div style='width: 100%;'>
  <div id="map" style='width: 100%; height: 700px;'></div>
</div>

<div id="data">
  <%= render partial: "show_data" %>
  <script type="text/javascript">
    var vehicles = [
      <% @vehicles.each do |v| %>
        ['<%= v.identifier %>', <%= v.last_waypoint.latitude %>, <%= v.last_waypoint.longitude %>, <%= v.id %>],
      <% end %>
    ];


    // Create a map object and specify the DOM element for display.
    var map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: vehicles[0][1], lng: vehicles[0][2]},
      zoom: 8
    });
    // Adds markers to the map.
    var bounds = new google.maps.LatLngBounds();
    for (var i = 0; i < vehicles.length; i++) {
      var vehicle = vehicles[i];
      var marker = new google.maps.Marker({
        position: {lat: vehicle[1], lng: vehicle[2]},
        map: map,
        label: {
          color: 'red',
          fontWeight: 'bold',
          text: vehicle[0],
        },        
        title: vehicle[0],
        zIndex: vehicle[3]
      });
      bounds.extend(marker.getPosition());
    }    

    map.fitBounds(bounds);
  </script>
</div>

app/views/vehicles/index.js.erb
$("#data").html("<%= escape_javascript(render(:partial => 'show_data')) %>");

var vehicles = [
  <% @vehicles.each do |v| %>
    ['<%= v.identifier %>', <%= v.last_waypoint.latitude %>, <%= v.last_waypoint.longitude %>, <%= v.id %>],
  <% end %>
];


// Create a map object and specify the DOM element for display.
var map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: vehicles[0][1], lng: vehicles[0][2]},
  zoom: 8
});
// Adds markers to the map.
var bounds = new google.maps.LatLngBounds();
for (var i = 0; i < vehicles.length; i++) {
  var vehicle = vehicles[i];
  var marker = new google.maps.Marker({
    position: {lat: vehicle[1], lng: vehicle[2]},
    map: map,
    label: {
      color: 'red',
      fontWeight: 'bold',
      text: vehicle[0],
    },
    title: vehicle[0],
    zIndex: vehicle[3]
  });
  bounds.extend(marker.getPosition());
}    

map.fitBounds(bounds);

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identifier:</strong>
  <%= @vehicle.identifier %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>

app/views/waypoints/_form.html.erb
<%= form_with(model: waypoint, local: true) do |form| %>
  <% if waypoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(waypoint.errors.count, "error") %> prohibited this waypoint from being saved:</h2>

      <ul>
      <% waypoint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :waypoint_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :waypoint_longitude %>
  </div>

  <div class="field">
    <%= form.label :sent_at %>
    <%= form.datetime_select :sent_at, id: :waypoint_sent_at %>
  </div>

  <div class="field">
    <%= form.label :vehicle_id %>
    <%= form.text_field :vehicle_id, id: :waypoint_vehicle_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/waypoints/edit.html.erb
<h1>Editing Waypoint</h1>

<%= render 'form', waypoint: @waypoint %>

<%= link_to 'Show', @waypoint %> |
<%= link_to 'Back', waypoints_path %>

app/views/waypoints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Waypoints</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Sent at</th>
      <th>Vehicle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waypoints.each do |waypoint| %>
      <tr>
        <td><%= waypoint.latitude %></td>
        <td><%= waypoint.longitude %></td>
        <td><%= waypoint.sent_at %></td>
        <td><%= waypoint.vehicle %></td>
        <td><%= link_to 'Show', waypoint %></td>
        <td><%= link_to 'Edit', edit_waypoint_path(waypoint) %></td>
        <td><%= link_to 'Destroy', waypoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Waypoint', new_waypoint_path %>

app/views/waypoints/new.html.erb
<h1>New Waypoint</h1>

<%= render 'form', waypoint: @waypoint %>

<%= link_to 'Back', waypoints_path %>

app/views/waypoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @waypoint.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @waypoint.longitude %>
</p>

<p>
  <strong>Sent at:</strong>
  <%= @waypoint.sent_at %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @waypoint.vehicle %>
</p>

<%= link_to 'Edit', edit_waypoint_path(@waypoint) %> |
<%= link_to 'Back', waypoints_path %>